### ISSUE TITLE
Warnings that will become errors

### ISSUE THREAD

**Issue by kyp44** [DDOtten/partitions#2]
It looks like the latest commit for this crate was over four years ago, so I'm not sure whether it's still being maintained.

It looks like it contains some compiler warnings (which may not have been warnings at the time) that are soon going to become compiler errors. These looks like very simple fixes, so if you like I'm happy to submit a PR to fix these if you'd accept it.

EDIT: To clarify, I am building on nightly so I don't know whether these are flagged currently in stable.

**Comment by spencer3035** [comment]
I fixed the warnings/future errors. Marked as a draft for now. I am hapy to mark as final after peer review.

**Comment by rytse** [comment]
Could we get a new release that includes this change? Thanks!
